# The following line is needed to enable the theme
themesDir = "themes"

title = "exonymos"
theme = "too-much"
languageCode = "en-us"
baseURL = "https://exonymos.github.io/"
copyright = "exonymos © {year}"

[markup]
  [markup.highlight]
    style = 'dracula'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[params]
theme = "dark"
palette = "catpuccin"
showThemeNotice = true
showPostsSummary = true

[params.giscus]
repository = "Exonymos/projects"
repositoryId = "R_kgDOJfktVA"
categoryName = "General"
categoryId = "DIC_kwDOJfktVM4Ch7m6"
mapping = "pathname"
theme = "transparent_dark"
language = "en"
lazyLoading = true

[privacy]
  [privacy.x]
    disable = false
    enableDNT = true

# Navigation
[menu]
  [[menu.main]]
    identifier = "home"
    name = "home"
    title = "Home"
    url = "/"
    weight = 1
  
  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "About"
    url = "/about"
    weight = 2
  
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/posts"
    weight = 3
  
  [[menu.main]]
    identifier = "tags"
    name = "tags"
    title = "tags"
    url = "/tags"
    weight = 4
  
  [[menu.main]]
    identifier = "github"
    name = "github"
    title = "GitHub"
    url = "https://github.com/exonymos"
    weight = 5
